#ifndef __GNSS_DEF_H
#define __GNSS_DEF_H


/* 2.1.2. AT+QGNSSRD Read GNSS Navigation Information */
#define GNSS_NAVIGATION_PROTOCOL_GGA    "NMEA/GGA"
#define GNSS_NAVIGATION_PROTOCOL_GLL    "NMEA/GLL"
#define GNSS_NAVIGATION_PROTOCOL_GSA    "NMEA/GSA"
#define GNSS_NAVIGATION_PROTOCOL_GSV    "NMEA/GSV"
#define GNSS_NAVIGATION_PROTOCOL_RMC    "NMEA/RMC"
#define GNSS_NAVIGATION_PROTOCOL_VTG    "NMEA/VTG"


#endif